# Ex1 - Filtering and Sorting Data

This time we are going to pull data directly from the internet.
Special thanks to: https://github.com/justmarkham for sharing the dataset and materials.

### Step 1. Import the necessary libraries

In [1]:
import pandas as pd

### Step 2. Import the dataset from this [address](https://raw.githubusercontent.com/justmarkham/DAT8/master/data/u.user).

In [2]:
url = "https://raw.githubusercontent.com/thieu1995/csv-files/main/data/pandas/chipotle.tsv"

### Step 3. Assign it to a variable called chipo.

In [3]:
chipo = pd.read_csv(url, sep = '\t')

### Step 4. How many products cost more than $10.00?

In [4]:
# Kiểm tra kiểu dữ liệu của cột 'item_price' và chuyển đổi nếu cần
if chipo['item_price'].dtype == object:
    chipo['item_price'] = chipo['item_price'].str.replace('$', '').astype(float)

# Tạo cột mới 'price_per_item'
chipo['price_per_item'] = chipo['item_price'] / chipo['quantity']

# Xóa bản ghi trùng lặp
chipo_filtered = chipo.drop_duplicates(['item_name', 'quantity', 'choice_description'])

# Chọn các sản phẩm có số lượng bằng 1
chipo_one_prod = chipo_filtered[chipo_filtered['quantity'] == 1]

# Đếm số lượng sản phẩm có giá trên $10 mỗi món
number_of_unique_items = chipo_one_prod[chipo_one_prod['price_per_item'] > 10].item_name.nunique()
print("Số lượng món ăn có giá trên $10 mỗi món là:", number_of_unique_items)

Số lượng món ăn có giá trên $10 mỗi món là: 25

### Step 5. What is the price of each item?

In [5]:
chipo[(chipo['item_name'] == 'Chicken Bowl') & (chipo['quantity'] == 1)]

,order_id,quantity,item_name,choice_description,item_price,price_per_item
5,3,1,Chicken Bowl,"[Fresh Tomato Salsa (Mild), [Rice, Cheese, Sou...",10.98,10.98
13,7,1,Chicken Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Rice,...",11.25,11.25
19,10,1,Chicken Bowl,"[Tomatillo Red Chili Salsa, [Fajita Vegetables...",8.75,8.75
26,13,1,Chicken Bowl,"[Roasted Chili Corn Salsa (Medium), [Pinto Bea...",8.49,8.49
42,20,1,Chicken Bowl,"[Roasted Chili Corn Salsa, [Rice, Black Beans,...",11.25,11.25
...,...,...,...,...,...,...
4590,1825,1,Chicken Bowl,"[Roasted Chili Corn Salsa, [Rice, Black Beans,...",11.25,11.25
4591,1825,1,Chicken Bowl,"[Tomatillo Red Chili Salsa, [Rice, Black Beans...",8.75,8.75
4595,1826,1,Chicken Bowl,"[Tomatillo Green Chili Salsa, [Rice, Black Bea...",8.75,8.75
4599,1827,1,Chicken Bowl,"[Roasted Chili Corn Salsa, [Cheese, Lettuce]]",8.75,8.75
4604,1828,1,Chicken Bowl,"[Fresh Tomato Salsa, [Rice, Black Beans, Chees...",8.75,8.75

### Step 6. Sort by the name of the item

In [10]:
#solution 1:
chipo.item_name.sort_values()

3389    6 Pack Soft Drink
341     6 Pack Soft Drink
1849    6 Pack Soft Drink
1860    6 Pack Soft Drink
2713    6 Pack Soft Drink
              ...
2384    Veggie Soft Tacos
781     Veggie Soft Tacos
2851    Veggie Soft Tacos
1699    Veggie Soft Tacos
1395    Veggie Soft Tacos
Name: item_name, Length: 4622, dtype: object

In [9]:
#solution 2:
chipo.sort_values(by = "item_name")

,order_id,quantity,item_name,choice_description,item_price,price_per_item
3389,1360,2,6 Pack Soft Drink,[Diet Coke],12.98,6.49
341,148,1,6 Pack Soft Drink,[Diet Coke],6.49,6.49
1849,749,1,6 Pack Soft Drink,[Coke],6.49,6.49
1860,754,1,6 Pack Soft Drink,[Diet Coke],6.49,6.49
2713,1076,1,6 Pack Soft Drink,[Coke],6.49,6.49
...,...,...,...,...,...,...
2384,948,1,Veggie Soft Tacos,"[Roasted Chili Corn Salsa, [Fajita Vegetables,...",8.75,8.75
781,322,1,Veggie Soft Tacos,"[Fresh Tomato Salsa, [Black Beans, Cheese, Sou...",8.75,8.75
2851,1132,1,Veggie Soft Tacos,"[Roasted Chili Corn Salsa (Medium), [Black Bea...",8.49,8.49
1699,688,1,Veggie Soft Tacos,"[Fresh Tomato Salsa, [Fajita Vegetables, Rice,...",11.25,11.25
1395,567,1,Veggie Soft Tacos,"[Fresh Tomato Salsa (Mild), [Pinto Beans, Rice...",8.49,8.49

### Step 7. What was the quantity of the most expensive item ordered?

In [11]:
chipo.sort_values(by = "item_price", ascending = False).head(1)

,order_id,quantity,item_name,choice_description,item_price,price_per_item
3598,1443,15,Chips and Fresh Tomato Salsa,NaN,44.25,2.95

### Step 8. How many times was a Veggie Salad Bowl ordered?

In [13]:
chipo_salad = chipo[chipo.item_name == "Veggie Salad Bowl"]
len(chipo_salad)

18

### Step 9. How many times did someone order more than one Canned Soda?

In [14]:
chipo_Canned_Soda = chipo[(chipo.item_name == "Canned Soda") & (chipo.quantity > 1)]
len(chipo_Canned_Soda)

20